server:
  address: 192.168.1.162
  port: 8081

spring:
  application:
    name: gamification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/plantsocial_gamification
    username: plantsocial_user
    password: plantsocial_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
