server:
  port: 9000

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/plantsocial
  cloud:
    gateway:
      default-filters:
        # Safety net to prevent the "Double Bouncer" issue we fixed earlier
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        # FIX: Changed to kebab-case 'cors-configurations'
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:4200"
              - "http://192.168.1.250:4200"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "PATCH"
            # Allowing "*" headers is critical for the 'Authorization' token to pass through
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: centrifugo-ws
          uri: ws://localhost:8000
          predicates:
            - Path=/connection/**
        - id: chat-service-send
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/chat/send
            - Method=POST
        - id: backend_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
        - id: gamification_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/gamification/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
