server:
  port: 8083

spring:
  application:
    name: chat-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/plantsocial

centrifugo:
  api-url: http://plantsocial_centrifugo:8000/api
  api-key: plantsocial-internal-secret-key
